<?php

use Drupal\node\NodeInterface;

/**
 * Implements hook_ENTITY_TYPE_update() for node entities.
 *
 * Sends emails to users when changed to published.
 */
function cc_alerts_node_insert(NodeInterface $node) {

  if ($node->type->getValue()[0]['target_id'] == 'alerts') {
    $params['type_of_alert'] = $node->field_cc_alert_type->getValue()[0]['value'];
    $params['message'] = $node->field_cc_alert_text->getValue()[0]['value'];

    _cc_site_controller_send_emails('alert_created', $params);
  }
}

/**
 * Implements hook_ENTITY_TYPE_update() for node entities.
 *
 * Sends emails to users when changed to published.
 */
function cc_alerts_node_update(NodeInterface $node) {

  // If we are on a news, process it.
  if ($node->type->getValue()[0]['target_id'] == 'alerts') {

    // The updated nodes status.
    $node_status = $node->status->getValue()[0]['value'];

    if (isset($node->original->status->getValue()[0]['value']) && $node->original->status->getValue()[0]['value'] !== NULL) {
      $original_node_status = $node->original->status->getValue()[0]['value'];
    }
    else {
      $original_node_status = 0;
    }

    // If we are changing to a published node, send emails.
    if (!$original_node_status && $node_status) {

      $params['type_of_alert'] = $node->field_cc_alert_type->getValue()[0]['value'];
      $params['message'] = $node->field_cc_alert_text->getValue()[0]['value'];

      _cc_site_controller_send_emails('alert_created', $params);
    }
  }
}
